- libio: misc: correct `strftime` format for non-portable GNU `%-e` specifier

diff --git a/configure b/configure
--- a/configure
+++ b/configure
@@ -841,6 +841,7 @@ enable_debugging
 enable_warnings
 enable_efence
 with_tls
+with_strftime_minus_e
 '
       ac_precious_vars='build_alias
 host_alias
@@ -1521,6 +1522,8 @@ Optional Packages:
   --with-ltdl-lib=DIR     use the libltdl.la installed in DIR
   --with-tls              Enables TLS with specified library. Options:
                           'openssl', 'wolfssl', 'gnutls' or 'none'
+  --with-strftime-minus-e Control the check for GNU strftime %-e support
+                          [auto/yes/no]
 
 Some influential environment variables:
   CC          C compiler command
@@ -19629,6 +19632,93 @@ printf "%s\n" "#define LOCALSTATEDIR \"$ax_define_dir\"" >>confdefs.h
 
 printf "%s\n" "#define AX_BUILD_DATE \"$BUILD_DATE\"" >>confdefs.h
 
+
+
+
+
+# Check whether --with-strftime-minus-e was given.
+if test ${with_strftime_minus_e+y}
+then :
+  withval=$with_strftime_minus_e;
+else case e in #(
+  e) with_strftime_minus_e=auto
+   ;;
+esac
+fi
+
+
+  { printf "%s\n" "$as_me:${as_lineno-$LINENO}: checking for GNU-style “%-e” no-padding day-of-month" >&5
+printf %s "checking for GNU-style “%-e” no-padding day-of-month... " >&6; }
+if test ${ax_cv_func_strftime_minus_e+y}
+then :
+  printf %s "(cached) " >&6
+else case e in #(
+  e)
+      ax_cv_func_strftime_minus_e="$with_strftime_minus_e"
+
+      if test "x$ax_cv_func_strftime_minus_e" = xauto
+then :
+
+        if test "$cross_compiling" = yes
+then :
+
+            ax_cv_func_strftime_minus_e=no
+            { printf "%s\n" "$as_me:${as_lineno-$LINENO}: WARNING: Cannot run test for strftime %-e support." >&5
+printf "%s\n" "$as_me: WARNING: Cannot run test for strftime %-e support." >&2;}
+            { printf "%s\n" "$as_me:${as_lineno-$LINENO}: WARNING: Assuming 'no'. Use --with-strftime-minus-e=yes to override." >&5
+printf "%s\n" "$as_me: WARNING: Assuming 'no'. Use --with-strftime-minus-e=yes to override." >&2;}
+
+
+else case e in #(
+  e) cat confdefs.h - <<_ACEOF >conftest.$ac_ext
+/* end confdefs.h.  */
+#include <time.h>
+              #include <string.h>
+              #include <stdio.h>
+
+int
+main (void)
+{
+
+              char buf[32];
+              struct tm tm;
+              memset(&tm, 0, sizeof(tm));
+              tm.tm_mday = 2; tm.tm_mon = 0; tm.tm_year = 100;
+              if (strftime(buf, sizeof(buf), "%-e", &tm) > 0 && strcmp(buf, "2") == 0)
+                return 0;
+              return 1;
+
+
+  ;
+  return 0;
+}
+_ACEOF
+if ac_fn_c_try_run "$LINENO"
+then :
+  ax_cv_func_strftime_minus_e=yes
+else case e in #(
+  e) ax_cv_func_strftime_minus_e=no ;;
+esac
+fi
+rm -f core *.core core.conftest.* gmon.out bb.out conftest$ac_exeext \
+  conftest.$ac_objext conftest.beam conftest.$ac_ext ;;
+esac
+fi
+
+
+fi
+
+   ;;
+esac
+fi
+{ printf "%s\n" "$as_me:${as_lineno-$LINENO}: result: $ax_cv_func_strftime_minus_e" >&5
+printf "%s\n" "$ax_cv_func_strftime_minus_e" >&6; }
+
+  if test "x$ax_cv_func_strftime_minus_e" = xyes; then
+
+printf "%s\n" "#define HAVE_STRFTIME_MINUS_E 1" >>confdefs.h
+
+  fi
 
 
 ac_config_files="$ac_config_files Makefile doc/Makefile help/Makefile libio/Makefile libio/src/Makefile libltdl/Makefile modules/Makefile src/Makefile tools/Makefile"
